name: "Setup project"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: "5.x"

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      id: version
      with:
        useConfigFile: true

    - name: Use the version
      shell: bash
      run: |
        echo VITE_SZ_VERSION="${{ steps.version.outputs.AssemblySemFileVer }}" >> $GITHUB_ENV
        echo VITE_SZ_VERSION_INFO="${{ steps.version.outputs.InformationalVersion }}" >> $GITHUB_ENV

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 9
        run_install: false

    - uses: actions/setup-node@v3
      with:
        node-version: "20"
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Linter
      shell: bash
      run: pnpm lint
